/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteRouteImport } from './routes/chat/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as RecentIndexRouteImport } from './routes/recent/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiCompletionRouteImport } from './routes/api/completion'
import { Route as ChatThreadIdIndexRouteImport } from './routes/chat/$threadId/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFilesFileIdIndexRouteImport } from './routes/api/files/$fileId/index'
import { Route as ApiFilesFileIdContentRouteImport } from './routes/api/files/$fileId/content'

const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentIndexRoute = RecentIndexRouteImport.update({
  id: '/recent/',
  path: '/recent/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRouteRoute,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompletionRoute = ApiCompletionRouteImport.update({
  id: '/api/completion',
  path: '/api/completion',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdIndexRoute = ChatThreadIdIndexRouteImport.update({
  id: '/$threadId/',
  path: '/$threadId/',
  getParentRoute: () => ChatRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesFileIdIndexRoute = ApiFilesFileIdIndexRouteImport.update({
  id: '/$fileId/',
  path: '/$fileId/',
  getParentRoute: () => ApiFilesRoute,
} as any)
const ApiFilesFileIdContentRoute = ApiFilesFileIdContentRouteImport.update({
  id: '/$fileId/content',
  path: '/$fileId/content',
  getParentRoute: () => ApiFilesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteRouteWithChildren
  '/api/completion': typeof ApiCompletionRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/chat/': typeof ChatIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/recent/': typeof RecentIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/chat/$threadId/': typeof ChatThreadIdIndexRoute
  '/api/files/$fileId/content': typeof ApiFilesFileIdContentRoute
  '/api/files/$fileId/': typeof ApiFilesFileIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/completion': typeof ApiCompletionRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/chat': typeof ChatIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/recent': typeof RecentIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/terms': typeof TermsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/chat/$threadId': typeof ChatThreadIdIndexRoute
  '/api/files/$fileId/content': typeof ApiFilesFileIdContentRoute
  '/api/files/$fileId': typeof ApiFilesFileIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteRouteWithChildren
  '/api/completion': typeof ApiCompletionRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/chat/': typeof ChatIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/recent/': typeof RecentIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/chat/$threadId/': typeof ChatThreadIdIndexRoute
  '/api/files/$fileId/content': typeof ApiFilesFileIdContentRoute
  '/api/files/$fileId/': typeof ApiFilesFileIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/api/completion'
    | '/api/files'
    | '/chat/'
    | '/privacy/'
    | '/recent/'
    | '/sign-in/'
    | '/terms/'
    | '/api/auth/$'
    | '/chat/$threadId/'
    | '/api/files/$fileId/content'
    | '/api/files/$fileId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/completion'
    | '/api/files'
    | '/chat'
    | '/privacy'
    | '/recent'
    | '/sign-in'
    | '/terms'
    | '/api/auth/$'
    | '/chat/$threadId'
    | '/api/files/$fileId/content'
    | '/api/files/$fileId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/api/completion'
    | '/api/files'
    | '/chat/'
    | '/privacy/'
    | '/recent/'
    | '/sign-in/'
    | '/terms/'
    | '/api/auth/$'
    | '/chat/$threadId/'
    | '/api/files/$fileId/content'
    | '/api/files/$fileId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRouteRoute: typeof ChatRouteRouteWithChildren
  ApiCompletionRoute: typeof ApiCompletionRoute
  ApiFilesRoute: typeof ApiFilesRouteWithChildren
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  RecentIndexRoute: typeof RecentIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent/': {
      id: '/recent/'
      path: '/recent'
      fullPath: '/recent/'
      preLoaderRoute: typeof RecentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/completion': {
      id: '/api/completion'
      path: '/api/completion'
      fullPath: '/api/completion'
      preLoaderRoute: typeof ApiCompletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId/': {
      id: '/chat/$threadId/'
      path: '/$threadId'
      fullPath: '/chat/$threadId/'
      preLoaderRoute: typeof ChatThreadIdIndexRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$fileId/': {
      id: '/api/files/$fileId/'
      path: '/$fileId'
      fullPath: '/api/files/$fileId/'
      preLoaderRoute: typeof ApiFilesFileIdIndexRouteImport
      parentRoute: typeof ApiFilesRoute
    }
    '/api/files/$fileId/content': {
      id: '/api/files/$fileId/content'
      path: '/$fileId/content'
      fullPath: '/api/files/$fileId/content'
      preLoaderRoute: typeof ApiFilesFileIdContentRouteImport
      parentRoute: typeof ApiFilesRoute
    }
  }
}

interface ChatRouteRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatThreadIdIndexRoute: typeof ChatThreadIdIndexRoute
}

const ChatRouteRouteChildren: ChatRouteRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatThreadIdIndexRoute: ChatThreadIdIndexRoute,
}

const ChatRouteRouteWithChildren = ChatRouteRoute._addFileChildren(
  ChatRouteRouteChildren,
)

interface ApiFilesRouteChildren {
  ApiFilesFileIdContentRoute: typeof ApiFilesFileIdContentRoute
  ApiFilesFileIdIndexRoute: typeof ApiFilesFileIdIndexRoute
}

const ApiFilesRouteChildren: ApiFilesRouteChildren = {
  ApiFilesFileIdContentRoute: ApiFilesFileIdContentRoute,
  ApiFilesFileIdIndexRoute: ApiFilesFileIdIndexRoute,
}

const ApiFilesRouteWithChildren = ApiFilesRoute._addFileChildren(
  ApiFilesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRouteRoute: ChatRouteRouteWithChildren,
  ApiCompletionRoute: ApiCompletionRoute,
  ApiFilesRoute: ApiFilesRouteWithChildren,
  PrivacyIndexRoute: PrivacyIndexRoute,
  RecentIndexRoute: RecentIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
